src/integrations/cohttp/opentelemetry_cohttp_lwt.ml, tests/bin/cohttp_client.ml, tests/bin/dune
API for discussion. The idea is that you call `Opentelemetry_cohttp_lwt.client` and it gives you back a traced version of `Cohttp_lwt.Client`.
The downside is that you have to do this at every call to include the current scope:
```ocaml
let mk_client ?scope () =
Opentelemetry_cohttp_lwt.client ?scope (module Cohttp_lwt_unix.Client)
let f ~scope =
let (module C) = mk_client ~scope () in
C.get (Uri.of_string "https://google.com")
```
The upside is that you can trace calls made with `Cohttp_lwt` in 3rd party libraries without those libraries knowing about `Opentelemetry`, as long as those libraries are functorized over `Cohttp_lwt.S.Client`.
See for example https://github.com/AestheticIntegration/ocaml-kubernetes/commit/f0d74fb72c399edc6f153702f4e197911901ba85:
```ocaml
let f ~scope ~config …
```
=> Integration with cohttp-lwt (client)

src/lwt/opentelemetry_lwt.ml, src/opentelemetry.ml
For convenience. If you pass both `~trace_id`/`~parent` and `~scope`, the former take priority.
=> feat: allow passing ~scope back to Trace.with_

src/client/opentelemetry_client_ocurl.ml, src/opentelemetry.ml
See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#runtime-environment-specific-metrics---processruntimeenvironment
=> feat: use runtime metric conventions; add runtime attributes

src/client/common_.ml, src/client/config.ml, src/client/config.mli, src/client/opentelemetry_client_ocurl.ml, src/client/opentelemetry_client_ocurl.mli
This can be done through the API or by setting `OTEL_EXPORTER_OTLP_HEADERS`
This is needed to export data to new relic, for example: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/
=> feat: Allow setting API headers

src/dune, src/integrations/cohttp/opentelemetry_cohttp_lwt.ml, src/lwt/opentelemetry_lwt.ml, src/opentelemetry.ml, src/thread_local.ml, src/thread_local.mli, tests/bin/emit1.ml
basic thread local storage so that we don't have to carry `?scope` around.
=> implicit scope using TLS

src/client-cohttp-lwt/common_.ml, src/client-ocurl/common_.ml
I was trying to use the library with elastic's [APM offering](https://www.elastic.co/observability/application-performance-monitoring) and I noticed errors related to authentication. Elastic's APM integration expected an authorization header of the form `Authorization=Bearer <token>`. The existing header parsing implementation in the library would discard anything after the first space and parsed this header as `(Authorization, Bearer)`. With the patch in this pull-request I was able to successfully push traces and logs to Elastic APM.
=> Allow spaces in header values set via `OTEL_EXPORTER_OTLP_HEADERS` 

dune-project, opentelemetry-client-cohttp-lwt.opam, opentelemetry-lwt.opam, src/client-cohttp-lwt/common_.ml, src/client-cohttp-lwt/dune, src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/lwt/dune, src/lwt/opentelemetry_lwt.ml
The Lwt docs [recommend](https://ocaml.org/p/lwt/5.5.0/doc/Lwt/index.html#rejection) the PPX over the function-call;
> Despite the above code, the recommended way to write Lwt.catch is using the try%lwt syntactic sugar from the [PPX](https://ocaml.org/p/lwt/5.5.0/doc/Lwt/Ppx_lwt.html).
That said, mainly a stylistic difference in this case. Feel free to just close if you're not a fan. (=
=> Use try%lwt over Lwt.catch

src/client-ocurl/opentelemetry_client_ocurl.ml
Uses named signals from the `Sys` module instead of hardcoded numbers.
=> use named signals

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-ocurl/opentelemetry_client_ocurl.ml, tests/dune, tests/test_get_url.expected, tests/test_get_url.ml
Specifying an `url` to the config
```ocaml
Config.make ~url:"http://localhost:3000"
```
And then calling `get_url()` returns the default URL (or `OTEL_EXPORTER_OTLP_ENDPOINT` if provided). It would make more sense to me to show the URL from the config since that's the one actually used.
* [First commit](https://github.com/imandra-ai/ocaml-opentelemetry/commit/9c8776fde4c38363c4e8c4532def5eda1718b403) add a test (not sure if it's worth a test 😅)
* [Second commit](https://github.com/imandra-ai/ocaml-opentelemetry/pull/40/commits/85fa4996f4b8e08426e73646bb58479417e0c6fc) is the actual fix
=> get_url returns url from config if provided

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-ocurl/config.ml, src/client-ocurl/config.mli, src/client-ocurl/opentelemetry_client_ocurl.ml, src/core/AList.ml, src/core/AList.mli, src/core/opentelemetry.ml, tests/bin/emit1.ml
this introduces:
- self-tracing for the ocurl backend
- GC metrics are collected on tick, not on GC signal (more regular)
- new config options for ocurl backend (self tracing, and tick interval)
=> perf and features

.github/workflows/main.yml, src/core/opentelemetry.ml, src/lwt/opentelemetry_lwt.ml, src/trace/opentelemetry_trace.ml
=> support trace 0.6

src/core/opentelemetry.ml, tests/core/test_trace_context.expected, tests/core/test_trace_context.ml
- feat: add Span_context, as required by OTEL API guidelines
- perf: rewrite parsing+printing for span ctx as w3c trace ctx
- test: update test output
=> add span context, rewrite w3c trace context

src/trace/opentelemetry_trace.ml, src/trace/opentelemetry_trace.mli
make otel-trace a bit more lightweight by avoiding redundant fields
=> update a bit opentelemetry.trace

src/trace/opentelemetry_trace.ml
Hello, we wanted to use the tracing frontend, with the option to add otel events to the otel spans. It turns out that when spans are created in the otel tracing backend, events aren't passed through from the scope. This fixes that.
=> Add events to spans created in trace frontend

dune-project, opentelemetry-lwt.opam
I think this is a leftover from https://github.com/imandra-ai/ocaml-opentelemetry/pull/59
=> remove leftover ambient-context dependency

src/client-ocurl/opentelemetry_client_ocurl.ml, src/core/opentelemetry.ml, src/integrations/cohttp/opentelemetry_cohttp_lwt.ml, src/trace/opentelemetry_trace.ml
As discussed, I'll try to implement the structure change in a subsequent PR
=> add links to scope

src/client-ocurl/opentelemetry_client_ocurl.ml, src/core/opentelemetry.ml, src/trace/opentelemetry_trace.ml
This is my take at implementing your suggestion to reduce `Scope.t` memory usage
=> reduce memory usage of Scope.t

src/trace/opentelemetry_trace.ml
=> fix otel.trace: record exception in `with_span`

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-ocurl/opentelemetry_client_ocurl.ml
this helps flushing signals that are being batched.
close #69
=> in backends, call tick() before cleaning up

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-ocurl/opentelemetry_client_ocurl.ml, src/core/opentelemetry.ml
=> feat: allow to remove backend

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.mli, tests/bin/cohttp_client.ml, tests/bin/emit1_cohttp.ml
in `Opentelemetry_client_cohttp_lwt.with_setup` we should now wait for
the cleanup to be done, by sneaking in a `unit Lwt.u` that is only
resolved after the cleanup is done.
close #41
=> fix: wait for cleanup in cohttp client

src/core/opentelemetry.ml
Otherwise we must get them from `Proto.Trace` which is quite annoying. Something I overlooked in the initial PR, sorry
=> expose Span_status types

src/core/opentelemetry.ml, src/trace/opentelemetry_trace.ml, src/trace/opentelemetry_trace.mli
- feat otel: add `Span_kind.t`, add {kind,set_kind} to `Scope`
- feat otel.trace: extension points for links, record_exn, kind
=> add extensions to otel.trace

src/core/opentelemetry.ml
Add support for the [sampled flag](https://www.w3.org/TR/trace-context/#sampled-flag)
=> support sampled flag

dune-project, opentelemetry-cohttp-lwt.opam
I reinstalled the project into my new laptop and got the following error (+ some extra alerts)
```sh
File "src/integrations/cohttp/opentelemetry_cohttp_lwt.ml", line 231, characters 10-16:
231 |   (module Traced : Cohttp_lwt.S.Client)
^^^^^^
Error: Signature mismatch:
...
The type `io' is required but not provided
File "cohttp-lwt/src/s.ml", line 199, characters 11-32:
Expected declaration
The type `with_context' is required but not provided
File "cohttp-lwt/src/s.ml", line 201, characters 11-48:
Expected declaration
The type `body' is required but not provided
File "cohttp-lwt/src/s.ml", line 200, characters 11-29:
Expected declaration
The value `map_context' is required but not provided
File "cohttp/src/client.ml", line 8, characters 2-68:
Expected declaration
The value `set_cache' is …
```
=> add cohttp upper bound version constraint

src/client-ocurl/opentelemetry_client_ocurl.ml
As of OCaml 5.3, the OCaml runtime doesn't support signals on Windows. Trying to block them with `Thread.sigmask` will raise:
Thread 5 killed on uncaught exception Invalid_argument("Thread.sigmask not implemented")
Raised by primitive operation at Opentelemetry_client_ocurl.start_bg_thread.run in file "src/client-ocurl/opentelemetry_client_ocurl.ml", line 106, characters 12-49
=> fix: opentelemetry-client-ocurl: don't block signals on Windows

src/ambient-context/eio/opentelemetry_ambient_context_eio.ml, src/core/opentelemetry.ml
Fix the `unused-module` warning
```
File "src/ambient-context/eio/opentelemetry_ambient_context_eio.ml", line 1, characters 0-33:
1 | module TLS = Thread_local_storage
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Warning 60 [unused-module]: unused module TLS.
``` 
and the `misplaced-attribute` warning
```
Warning 53 [misplaced-attribute]: the "deprecated" attribute cannot appear in this context
File "src/core/opentelemetry.ml", line 1229, characters 37-47:
1229 |   let add_event = Scope.add_event [@@deprecated "use Scope.add_event"]
^^^^^^^^^^
Warning 53 [misplaced-attribute]: the "deprecated" attribute cannot appear in this context
File "src/core/opentelemetry.ml", line 1231, characters 37-47:
1231 |   let add_attrs = Scope.add_attrs [@@deprecated "use Scope.add_attrs"]
^^^^^^^^^^
Warning 53 …
```
=> Fix a few build warnings

src/client-cohttp-lwt/opentelemetry_client_cohttp_lwt.ml, src/client-ocurl/opentelemetry_client_ocurl.ml, src/client/client.ml, src/client/dune, src/client/self_trace.ml, src/client/self_trace.mli, src/client/signal.ml, src/client/signal.mli
This removes some duplication in the logic around generating protobuf messages
to send over the wire. This is preparatory for moving a lot of the logic around
prepping signals out of the individual clients.
=> Factor out the logic around signal encoding

src/core/opentelemetry.ml
this brings the exception attributes in line with the spec https://opentelemetry.io/docs/specs/semconv/exceptions/exceptions-spans/. It seems we were missing the preceding `exception.`
=> fix: opentelemetry exception attr spec

src/client-cohttp-eio/opentelemetry_client_cohttp_eio.ml, src/client-cohttp-eio/opentelemetry_client_cohttp_eio.mli, tests/bin/emit1_cohttp.ml, tests/bin/emit1_eio.ml, tests/client_e2e/clients_e2e_lib.ml, tests/client_e2e/test_cottp_eio_client_e2e.ml, tests/client_e2e/test_cottp_lwt_client_e2e.ml
The initial implementation of the Eio collector I introduced in https://github.com/imandra-ai/ocaml-opentelemetry/pull/98 was not usable with signals emitted across domains. This was due to the fact that `Eio.Switch.t` is not thread-safe, and cannot be used across domains, but the implementation passed a switch into the `Collector.Backend`, which is then accessed across domains:
https://github.com/imandra-ai/ocaml-opentelemetry/blob/46d1289d953c59a7e4d2d8727a5e868559457bea/src/client-cohttp-eio/opentelemetry_client_cohttp_eio.ml#L476-L479
Consequently, the core fix introduced here is just to avoid sending a switch created from one domain into a reference that can be accessed from other domains.
However, it took me a bit of careful thinking thru the code flow to fully isolate this problem, …
=> Fix Eio collector to work accross domains

src/core/opentelemetry.ml
I *think* use of a non-threadsafe mutable reference for the metrics callbacks was resulting in a race condition that would sometimes produce non-deterministic results in the integration tests.
I suspect this has not affected the lwt-based collector, because of the single threaded concurrency Lwt enforces, but it began to show up in the WIP Eio rewrite, for which I am testing on cross-domain programs.
I suspect this may have also bee affecting the ocurl collector, but we don't have integration test running on that yet.
cc/ @c-cube
=> fix: make metric callbacks atomic
